services:
  broker:
    image: apache/kafka:latest
    container_name: kafka-broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092 # порт по которому можно подключится к брокеру
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - internal


  testing-service:
    build: ./testing-service
    container_name: testing-service
    depends_on:
      - broker
    networks:
      - internal
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092

  submission-acceptor-service:
    build: ./submission-aceptor-service
    container_name: submission-acceptor-service
    depends_on:
      - broker
    networks:
      - internal
      - external
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
    ports:
      - "1234:1234"


networks:
  internal:
    driver: bridge
  external:
    driver: bridge

#services:
#  broker:
#    image: apache/kafka:latest
#    container_name: kafka-broker
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_NODE_ID: 1
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#
##      # ДОБАВЬТЕ ЭТИ НАСТРОЙКИ:
##      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
##      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
##      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
##      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
##      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"