services:
  broker:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"
    networks:
      - external

  db:
    image: postgres
    restart: always
    ports:
      - "54342:5432"
    environment:
      POSTGRES_PASSWORD: root
    networks:
      - external

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8070:8080"
    networks:
      - external

  # testing-service:
  #   build: ./testing-service
  #   container_name: testing-service
  #   networks:
  #     - external
  #   depends_on:
  #     - db
  #   environment:
  #     KAFKA_BOOTSTRAP: kafka:9092
  #     POSTGRES_ADDRESS: db

  submission-acceptor-service:
   build: ./submission-aceptor-service
   container_name: submission-acceptor-service
   depends_on:
     - db
   networks:
     - external
   environment:
     KAFKA_BOOTSTRAP: kafka:9092
     POSTGRES_ADDRESS: db
      
   ports:
      - "1234:1234"


networks:
  external:
    driver: bridge
